import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';

const repoRoot = process.cwd();
const read = (relativePath) => fs.readFileSync(path.join(repoRoot, relativePath), 'utf8');

const participantView = read('src/components/session/messaging/ParticipantMessagingView.tsx');
const hostContent = read('src/components/session/host/HostSessionContent.tsx');
const preSessionHostView = read('src/components/session/host/PreSessionHostView.tsx');
const facilitatorVoice = read('src/hooks/facilitator/useFacilitatorVoice.ts');
const stylesheet = read('src/index.css');
const videoGrid = read('src/components/session/video/SessionVideoGrid.tsx');
const webRTCSessionHook = read('src/hooks/useWebRTCSession.ts');
const phase3RuntimeService = read('src/services/facilitator/phase3RuntimeService.ts');
const apiClient = read('src/lib/api.ts');
const vercelConfig = read('vercel.json');
const realtimeHelpers = read('src/utils/realtimeHelpers.ts');
const fastApiServer = read('supabase_proxy/server_fastapi.py');

const assertContains = (source, needle, label) => {
  assert.ok(source.includes(needle), `${label} should include ${needle}`);
};

const assertNotContains = (source, needle, label) => {
  assert.ok(!source.includes(needle), `${label} should not include ${needle}`);
};

assertContains(participantView, 'AI spotlight', 'participant view documentation');
assertContains(participantView, 'bg-slate-50 text-slate-950', 'participant light shell surface');
assertContains(participantView, 'Current question', 'participant current-question card');
assertContains(participantView, 'latestOwnParticipantMessage', 'participant registered-response derivation');
assertContains(participantView, 'String(message.participant) === participantKey', 'participant response registration tolerates numeric participant ids');
assertContains(participantView, 'Your response is registered', 'participant visible response confirmation');
assertContains(participantView, 'effectiveResponseCount', 'participant response counter uses local registration fallback');
assertContains(participantView, 'Math.max(responseCount, hasRegisteredResponse ? 1 : 0)', 'participant local response counter does not remain at zero after own reply registers');
assertContains(participantView, "type SidebarTab = 'people' | 'chat'", 'participant people/chat sidebar contract');
assertContains(participantView, '<SessionVideoGrid', 'participant People tab multi-video grid integration');
assertContains(participantView, 'variant="participant-sidebar"', 'participant sidebar video grid variant');
assertContains(participantView, 'participantVideoTiles', 'participant data-driven video tile mapping');
assertContains(participantView, 'navigator.mediaDevices.getUserMedia', 'participant local camera permission request');
assertContains(participantView, 'localCameraStartPromiseRef', 'participant camera permission requests are single-flight guarded');
assertContains(participantView, 'localCameraRequestIdRef.current !== requestId', 'participant camera ignores stale permission results');
assertContains(participantView, 'localCameraStartPromiseRef.current) return', 'participant camera toggle does not launch duplicate permission prompts while starting');
assertContains(participantView, 'localCameraStreamRef.current.getTracks().forEach((track) => track.stop())', 'participant local camera stream cleanup');
assertContains(participantView, 'data-camera-toggle="participant-local-preview"', 'participant header camera toggle marker');
assertContains(participantView, 'handleToggleLocalCameraClick', 'participant camera toggles use a guarded click handler');
assertContains(participantView, 'event.preventDefault();', 'participant camera toggle prevents accidental form submission or navigation');
assertContains(participantView, 'event.stopPropagation();', 'participant camera toggle avoids parent click side effects');
assertContains(participantView, 'useWebRTCSession({', 'participant initializes WebRTC signaling for remote video tiles');
assertContains(participantView, "role: 'participant'", 'participant WebRTC hook runs in participant role');
assertContains(participantView, 'mediaStream: isCurrentUser ? localCameraStream : remoteStream', 'participant self tile uses local stream and remote tiles use peer streams');
assertContains(participantView, 'roomConnectionLabel', 'participant exposes WebRTC room connection status for live QA');
assertContains(participantView, 'connectionStatusLabel', 'participant remote tiles expose peer connection labels');
assertContains(participantView, 'Camera access was blocked', 'participant camera permission feedback');
assertContains(participantView, 'animate-sound-bar', 'participant AI speaking visualization');
assertContains(participantView, '<InputFooter', 'participant preserved composer integration');
assertContains(participantView, 'submitModeInput={submitModeInput}', 'participant mode input plumbing');
assertContains(participantView, 'speechEnabled={speechStackEnabled}', 'participant speech runtime plumbing');
assertContains(participantView, 'hasTtsEventForMessage', 'participant skips facilitator TTS replay after refresh when a TTS event already exists');
assertContains(participantView, 'const messageId = String(lastAssistantMessage.id);', 'participant serializes assistant message id before speech tracking');
assertContains(participantView, 'lastSpokenAssistantMessageRef.current = messageId;', 'participant speech replay guard uses serialized message id');

assertContains(hostContent, 'PanelGroup direction="horizontal"', 'host resizable command center');
assertContains(hostContent, 'bg-slate-50 p-3 text-slate-950', 'host light command-center surface');
assertContains(hostContent, 'Participant intelligence', 'host participant intelligence rail');
assertContains(hostContent, 'Session pulse', 'host pulse panel');
assertContains(hostContent, '<SimplifiedHostMessagingView', 'host preserved control surface');
assertContains(hostContent, 'Video room', 'host multi-video room section');
assertContains(hostContent, "videoLayout === 'gallery'", 'host gallery-mode toggle');
assertContains(hostContent, '<SessionVideoTile', 'host spotlight video tile');
assertContains(hostContent, 'variant="host-strip"', 'host participant thumbnail strip');
assertContains(hostContent, 'showResponseStatus', 'host response status badges on video tiles');
assertContains(hostContent, 'useWebRTCSession({', 'host initializes WebRTC signaling for participant cameras');
assertContains(hostContent, "role: 'host'", 'host WebRTC hook runs in receive-only host role');
assertContains(hostContent, 'mediaStream: remoteStream', 'host participant video tiles consume remote MediaStreams');
assertContains(hostContent, 'const shouldEnableHostVideoRoom = Boolean(currentConversationId) && !isSessionEnded;', 'host WebRTC receiver stays enabled before formal session start so participant camera offers can complete');
assertContains(hostContent, 'enabled: shouldEnableHostVideoRoom', 'host WebRTC hook uses the pre-start receiver enablement guard');
assertNotContains(hostContent, 'enabled: isSessionStarted && !isSessionEnded', 'host WebRTC receiver must not stay disabled during pre-start participant camera checks');
assertContains(hostContent, 'videoRoomStatusLabel', 'host video room exposes WebRTC room connection status for live QA');
assertContains(hostContent, 'connectionStatusLabel: formatPeerTileStatusLabel(tileConnectionStatus)', 'host participant tiles expose peer connection labels');
assertContains(hostContent, 'onApproveMode={onApproveMode}', 'host mode approval plumbing');
assertContains(preSessionHostView, 'const isSessionStarted = Boolean(conversationData?.session_started);', 'pre-session host view derives live state from conversation data');
assertContains(preSessionHostView, 'isSessionStarted={isSessionStarted}', 'pre-session host start button reflects active sessions');
assertNotContains(preSessionHostView, 'isSessionStarted={false}', 'pre-session host start button must not be hard-coded inactive');
assertNotContains(hostContent, "UX handoff's dark", 'host design documentation');
assertNotContains(participantView, 'Precision Dark', 'participant design documentation');

assertContains(stylesheet, "font-family: 'Sora'", 'Signal & Clarity display font token');
assertContains(stylesheet, '@keyframes aiSpeakingPulse', 'AI speaking pulse animation');
assertContains(stylesheet, '@keyframes soundBar', 'sound bar animation');
assertContains(stylesheet, '@keyframes reactionPop', 'video reaction badge animation');

assertContains(videoGrid, 'mediaStream?: MediaStream | null', 'video tile optional live stream support');
assertContains(videoGrid, 'srcObject = stream', 'video tile MediaStream binding');
assertContains(videoGrid, 'videoElement.play()', 'video tile explicitly starts MediaStream playback after permission');
assertContains(videoGrid, 'videoElement.onloadedmetadata = playStream', 'video tile retries playback when stream metadata becomes available');
assertContains(videoGrid, 'srcObject = null', 'video tile MediaStream detaches on unmount');
assertContains(videoGrid, 'aria-label={`${name} live video`}', 'video tile accessible live preview label');
assertContains(videoGrid, "data-session-video-grid", 'video grid semantic marker');
assertContains(videoGrid, "data-video-tile-variant", 'video tile variant semantic marker');
assertContains(videoGrid, "variant?: 'participant-sidebar' | 'host-strip' | 'host-gallery'", 'video grid supported layout variants');
assertContains(videoGrid, 'data-connection-status={participant.connectionStatus}', 'video tile exposes peer connection status for smoke tests');
assertContains(videoGrid, 'connectionStatusLabel', 'video tile renders human-readable connection status labels');
assertContains(webRTCSessionHook, "event_type: WEBRTC_EVENT_TYPE", 'WebRTC signaling persists as session_events rows');
assertContains(webRTCSessionHook, "signalType: 'offer'", 'WebRTC hook sends SDP offers');
assertContains(webRTCSessionHook, "signalType: 'answer'", 'WebRTC hook sends SDP answers');
assertContains(webRTCSessionHook, "signalType: 'ice-candidate'", 'WebRTC hook sends ICE candidates');
assertContains(webRTCSessionHook, "signalType: 'camera-ready'", 'WebRTC hook supports camera-ready renegotiation hints');
assertContains(webRTCSessionHook, "signalType: 'camera-stopped'", 'WebRTC hook tears down remote streams when a camera stops');
assertContains(webRTCSessionHook, "filter: `conversation_id=eq.${conversationId}`", 'WebRTC realtime channel is scoped to the active conversation');
assertContains(webRTCSessionHook, 'WEBRTC_SIGNAL_RETENTION_MS', 'WebRTC hook defines stale signaling retention');
assertContains(webRTCSessionHook, 'WEBRTC_CAMERA_READY_BURST_COUNT', 'WebRTC hook repeats camera-ready hints to recover missed realtime inserts');
assertContains(webRTCSessionHook, 'WEBRTC_SIGNAL_CATCHUP_INTERVAL_MS', 'WebRTC hook polls recent persisted signals to recover missed realtime inserts');
assertContains(webRTCSessionHook, 'catchUpRecentSignals', 'WebRTC hook has a missed-signal catch-up path for late host/participant tabs');
assertContains(webRTCSessionHook, 'rememberSignal', 'WebRTC hook deduplicates realtime and catch-up signaling events');
assertContains(webRTCSessionHook, "connection.addTransceiver('video', { direction: videoTrack ? 'sendrecv' : 'recvonly' })", 'WebRTC hook creates stable video negotiation for camera-on and non-camera peers');
assertContains(webRTCSessionHook, ".delete()\n      .eq('conversation_id', conversationId)\n      .eq('event_type', WEBRTC_EVENT_TYPE)\n      .lt('created_at', cutoff)", 'WebRTC hook deletes stale session_events signals');
assertContains(webRTCSessionHook, 'VITE_WEBRTC_TURN_URLS', 'WebRTC hook supports deploy-time TURN server configuration');
assertContains(webRTCSessionHook, 'connectionStatus', 'WebRTC hook returns room-level connection status');
assertContains(webRTCSessionHook, 'peerStatuses', 'WebRTC hook returns per-peer connection status');
assertContains(webRTCSessionHook, 'diagnostics', 'WebRTC hook returns browser-visible diagnostics for video troubleshooting');
assertContains(webRTCSessionHook, 'localCandidateTypes', 'WebRTC hook captures local ICE candidate types for diagnostics');
assertContains(webRTCSessionHook, 'remoteCandidateTypes', 'WebRTC hook captures remote ICE candidate types for diagnostics');
assertContains(webRTCSessionHook, 'receiverTrackStates', 'WebRTC hook exposes receiver tracks in diagnostics when ICE connects without visible media');
assertContains(webRTCSessionHook, 'syncRemoteReceiverStream', 'WebRTC hook synthesizes remote streams from receiver tracks when ontrack stream payloads are missing');
assertContains(webRTCSessionHook, 'record.connection.getReceivers()', 'WebRTC hook inspects receiver tracks when ICE connects without a visible media stream');
assertContains(webRTCSessionHook, 'stream.addTrack(track);', 'WebRTC hook builds a fallback MediaStream from received remote tracks');
assertContains(webRTCSessionHook, 'WEBRTC_SIGNAL_CRITICAL_RETRY_COUNT', 'WebRTC hook retries critical SDP offer and answer inserts so participants do not remain stuck in have-local-offer');
assertContains(webRTCSessionHook, 'await syncLocalStreamToPeer(record, localStreamRef.current);', 'WebRTC answerer syncs local camera stream only after applying the remote offer');
assertContains(webRTCSessionHook, "role === 'participant' && peerId === HOST_PEER_ID", 'WebRTC participant actively creates the offer to the host when its camera is live');
assertContains(webRTCSessionHook, "role === 'host' && peerId !== HOST_PEER_ID", 'WebRTC host waits for participant offers to avoid glare and ghost peer bootstraps');
assertContains(webRTCSessionHook, 'if (!isLocalOffererForPeer(peerId)) return;', 'WebRTC createOffer is guarded so non-offerer reconnect paths cannot create glare');
assertContains(participantView, 'resolvePositiveParticipantId', 'Participant video shell rejects participant-0 identity fallbacks');
assertContains(participantView, 'getParticipantIdFromUrl', 'Participant video shell can recover the joined participant id from the URL');
assertContains(participantView, 'firstKnownParticipantId', 'Participant video shell falls back to the known participant record when identity is delayed');
assertContains(facilitatorVoice, 'waitForVoices', 'facilitator voice waits for async browser voice loading');
assertContains(facilitatorVoice, 'NATURAL_VOICE_KEYWORDS', 'facilitator voice prefers higher quality browser voices');
assertContains(facilitatorVoice, 'selectBestVoice', 'facilitator voice uses scored voice selection');
assertContains(facilitatorVoice, 'utterance.rate = 0.92', 'facilitator voice uses a calmer speaking rate');
assertContains(phase3RuntimeService, 'const serializedMessageId = input.messageId != null ? String(input.messageId) : null', 'TTS persistence serializes message ids before insertion');
assertContains(phase3RuntimeService, 'message_id: serializedMessageId', 'TTS persistence stores message ids as strings to match backend schema');
assertContains(phase3RuntimeService, 'export async function hasTtsEventForMessage', 'TTS runtime exposes refresh replay guard lookup');
assertContains(phase3RuntimeService, 'const serializedMessageId = String(messageId);', 'TTS replay guard serializes message ids before lookup');
assertContains(phase3RuntimeService, ".eq('message_id', serializedMessageId)", 'TTS replay guard queries by serialized message id');
assertContains(apiClient, 'RAILWAY_DEV_PROXY_PREFIX = "/__railway_dev"', 'API client defines same-origin dev Railway realtime proxy prefix');
assertContains(apiClient, 'RAILWAY_PROD_PROXY_PREFIX = "/__railway_prod"', 'API client defines same-origin production Railway realtime proxy prefix');
assertContains(apiClient, 'getRailwayRealtimeProxyPrefix', 'API client selects a same-origin realtime proxy on deployed browser origins');
assertContains(apiClient, 'buildRealtimeSseUrl(topic, token)', 'SSE subscriptions use centralized realtime URL construction');
assertContains(apiClient, 'new EventSource(url)', 'Realtime manager opens EventSource using the CORS-safe URL');
assertContains(apiClient, 'private normalizeFilterValue(col: string, val: unknown): unknown', 'API query builder centralizes table-specific filter serialization');
assertContains(apiClient, "this.s.table === 'facilitator_tts_events' && col === 'message_id'", 'API query builder serializes facilitator TTS message_id filters as strings');
assertContains(apiClient, 'private normalizeMutationBody(value: unknown): unknown', 'API query builder normalizes facilitator TTS mutation bodies');
assertContains(apiClient, 'next.message_id = String(next.message_id)', 'API query builder serializes facilitator TTS message_id mutation bodies as strings');
assertContains(apiClient, 'filter(col: string, op: string, val: unknown): this { this.filters.push([col, `${op}.${this.normalizeFilterValue(col, val)}`]); return this; }', 'Mutation builder serializes generic message_id filters as strings');
assertContains(apiClient, 'match(obj: Record<string, unknown>): this { Object.entries(obj).forEach(([k, v]) => this.filters.push([k, `eq.${this.normalizeFilterValue(k, v)}`])); return this; }', 'Mutation builder serializes message_id match filters as strings');
assertContains(fastApiServer, 'def build_where(params: dict, table: str | None = None):', 'Backend REST filters are table-aware for schema-specific coercion');
assertContains(fastApiServer, 'table == "facilitator_tts_events" and column == "message_id"', 'Backend REST filters keep facilitator TTS message_id as text');
assertContains(fastApiServer, 'table == "facilitator_tts_events" and k == "message_id" and v is not None', 'Backend REST writes keep facilitator TTS message_id as text');
assertContains(fastApiServer, 'wc, wv = build_where(params, table)', 'Backend REST handler passes table context into filter coercion');
assertContains(vercelConfig, '"source": "/__railway_dev/(.*)"', 'Vercel rewrites development realtime proxy before the SPA catch-all');
assertContains(vercelConfig, '"destination": "https://friendly-ai-sessions-development.up.railway.app/$1"', 'Vercel development proxy targets Railway dev backend');
assertContains(vercelConfig, '"source": "/__railway_prod/(.*)"', 'Vercel rewrites production realtime proxy before the SPA catch-all');
assertContains(vercelConfig, '"destination": "https://friendly-ai-sessions-production.up.railway.app/$1"', 'Vercel production proxy targets Railway production backend');
assertContains(vercelConfig, 'camera=(self)', 'deployed permissions policy allows same-origin participant camera preview');
assertContains(realtimeHelpers, 'void Promise.resolve(channel.unsubscribe()).catch(swallowExpectedRemovalError)', 'realtime helper catches async unsubscribe abort rejections');
assertContains(realtimeHelpers, 'void Promise.resolve(api.removeChannel(channel)).catch(swallowExpectedRemovalError)', 'realtime helper catches async removeChannel abort rejections');

console.log('UX session shell regression checks passed.');
