import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';

const repoRoot = process.cwd();
const read = (relativePath) => fs.readFileSync(path.join(repoRoot, relativePath), 'utf8');

const participantView = read('src/components/session/messaging/ParticipantMessagingView.tsx');
const hostContent = read('src/components/session/host/HostSessionContent.tsx');
const preSessionHostView = read('src/components/session/host/PreSessionHostView.tsx');
const facilitatorVoice = read('src/hooks/facilitator/useFacilitatorVoice.ts');
const stylesheet = read('src/index.css');
const videoGrid = read('src/components/session/video/SessionVideoGrid.tsx');
const webRTCSessionHook = read('src/hooks/useWebRTCSession.ts');
const phase3RuntimeService = read('src/services/facilitator/phase3RuntimeService.ts');
const vercelConfig = read('vercel.json');

const assertContains = (source, needle, label) => {
  assert.ok(source.includes(needle), `${label} should include ${needle}`);
};

const assertNotContains = (source, needle, label) => {
  assert.ok(!source.includes(needle), `${label} should not include ${needle}`);
};

assertContains(participantView, 'AI spotlight', 'participant view documentation');
assertContains(participantView, 'bg-slate-50 text-slate-950', 'participant light shell surface');
assertContains(participantView, 'Current question', 'participant current-question card');
assertContains(participantView, 'latestOwnParticipantMessage', 'participant registered-response derivation');
assertContains(participantView, 'String(message.participant) === participantKey', 'participant response registration tolerates numeric participant ids');
assertContains(participantView, 'Your response is registered', 'participant visible response confirmation');
assertContains(participantView, 'effectiveResponseCount', 'participant response counter uses local registration fallback');
assertContains(participantView, 'Math.max(responseCount, hasRegisteredResponse ? 1 : 0)', 'participant local response counter does not remain at zero after own reply registers');
assertContains(participantView, "type SidebarTab = 'people' | 'chat'", 'participant people/chat sidebar contract');
assertContains(participantView, '<SessionVideoGrid', 'participant People tab multi-video grid integration');
assertContains(participantView, 'variant="participant-sidebar"', 'participant sidebar video grid variant');
assertContains(participantView, 'participantVideoTiles', 'participant data-driven video tile mapping');
assertContains(participantView, 'navigator.mediaDevices.getUserMedia', 'participant local camera permission request');
assertContains(participantView, 'localCameraStreamRef.current.getTracks().forEach((track) => track.stop())', 'participant local camera stream cleanup');
assertContains(participantView, 'data-camera-toggle="participant-local-preview"', 'participant header camera toggle marker');
assertContains(participantView, 'handleToggleLocalCameraClick', 'participant camera toggles use a guarded click handler');
assertContains(participantView, 'event.preventDefault();', 'participant camera toggle prevents accidental form submission or navigation');
assertContains(participantView, 'event.stopPropagation();', 'participant camera toggle avoids parent click side effects');
assertContains(participantView, 'useWebRTCSession({', 'participant initializes WebRTC signaling for remote video tiles');
assertContains(participantView, "role: 'participant'", 'participant WebRTC hook runs in participant role');
assertContains(participantView, 'mediaStream: isCurrentUser ? localCameraStream : remoteStream', 'participant self tile uses local stream and remote tiles use peer streams');
assertContains(participantView, 'roomConnectionLabel', 'participant exposes WebRTC room connection status for live QA');
assertContains(participantView, 'connectionStatusLabel', 'participant remote tiles expose peer connection labels');
assertContains(participantView, 'Camera access was blocked', 'participant camera permission feedback');
assertContains(participantView, 'animate-sound-bar', 'participant AI speaking visualization');
assertContains(participantView, '<InputFooter', 'participant preserved composer integration');
assertContains(participantView, 'submitModeInput={submitModeInput}', 'participant mode input plumbing');
assertContains(participantView, 'speechEnabled={speechStackEnabled}', 'participant speech runtime plumbing');
assertContains(participantView, 'hasTtsEventForMessage', 'participant skips facilitator TTS replay after refresh when a TTS event already exists');
assertContains(participantView, 'const messageId = String(lastAssistantMessage.id);', 'participant serializes assistant message id before speech tracking');
assertContains(participantView, 'lastSpokenAssistantMessageRef.current = messageId;', 'participant speech replay guard uses serialized message id');

assertContains(hostContent, 'PanelGroup direction="horizontal"', 'host resizable command center');
assertContains(hostContent, 'bg-slate-50 p-3 text-slate-950', 'host light command-center surface');
assertContains(hostContent, 'Participant intelligence', 'host participant intelligence rail');
assertContains(hostContent, 'Session pulse', 'host pulse panel');
assertContains(hostContent, '<SimplifiedHostMessagingView', 'host preserved control surface');
assertContains(hostContent, 'Video room', 'host multi-video room section');
assertContains(hostContent, "videoLayout === 'gallery'", 'host gallery-mode toggle');
assertContains(hostContent, '<SessionVideoTile', 'host spotlight video tile');
assertContains(hostContent, 'variant="host-strip"', 'host participant thumbnail strip');
assertContains(hostContent, 'showResponseStatus', 'host response status badges on video tiles');
assertContains(hostContent, 'useWebRTCSession({', 'host initializes WebRTC signaling for participant cameras');
assertContains(hostContent, "role: 'host'", 'host WebRTC hook runs in receive-only host role');
assertContains(hostContent, 'mediaStream: remoteStream', 'host participant video tiles consume remote MediaStreams');
assertContains(hostContent, 'videoRoomStatusLabel', 'host video room exposes WebRTC room connection status for live QA');
assertContains(hostContent, 'connectionStatusLabel: formatPeerTileStatusLabel(tileConnectionStatus)', 'host participant tiles expose peer connection labels');
assertContains(hostContent, 'onApproveMode={onApproveMode}', 'host mode approval plumbing');
assertContains(preSessionHostView, 'const isSessionStarted = Boolean(conversationData?.session_started);', 'pre-session host view derives live state from conversation data');
assertContains(preSessionHostView, 'isSessionStarted={isSessionStarted}', 'pre-session host start button reflects active sessions');
assertNotContains(preSessionHostView, 'isSessionStarted={false}', 'pre-session host start button must not be hard-coded inactive');
assertNotContains(hostContent, "UX handoff's dark", 'host design documentation');
assertNotContains(participantView, 'Precision Dark', 'participant design documentation');

assertContains(stylesheet, "font-family: 'Sora'", 'Signal & Clarity display font token');
assertContains(stylesheet, '@keyframes aiSpeakingPulse', 'AI speaking pulse animation');
assertContains(stylesheet, '@keyframes soundBar', 'sound bar animation');
assertContains(stylesheet, '@keyframes reactionPop', 'video reaction badge animation');

assertContains(videoGrid, 'mediaStream?: MediaStream | null', 'video tile optional live stream support');
assertContains(videoGrid, 'srcObject = stream', 'video tile MediaStream binding');
assertContains(videoGrid, 'srcObject = null', 'video tile MediaStream detaches on unmount');
assertContains(videoGrid, 'aria-label={`${name} live video`}', 'video tile accessible live preview label');
assertContains(videoGrid, "data-session-video-grid", 'video grid semantic marker');
assertContains(videoGrid, "data-video-tile-variant", 'video tile variant semantic marker');
assertContains(videoGrid, "variant?: 'participant-sidebar' | 'host-strip' | 'host-gallery'", 'video grid supported layout variants');
assertContains(videoGrid, 'data-connection-status={participant.connectionStatus}', 'video tile exposes peer connection status for smoke tests');
assertContains(videoGrid, 'connectionStatusLabel', 'video tile renders human-readable connection status labels');
assertContains(webRTCSessionHook, "event_type: WEBRTC_EVENT_TYPE", 'WebRTC signaling persists as session_events rows');
assertContains(webRTCSessionHook, "signalType: 'offer'", 'WebRTC hook sends SDP offers');
assertContains(webRTCSessionHook, "signalType: 'answer'", 'WebRTC hook sends SDP answers');
assertContains(webRTCSessionHook, "signalType: 'ice-candidate'", 'WebRTC hook sends ICE candidates');
assertContains(webRTCSessionHook, "signalType: 'camera-ready'", 'WebRTC hook supports camera-ready renegotiation hints');
assertContains(webRTCSessionHook, "signalType: 'camera-stopped'", 'WebRTC hook tears down remote streams when a camera stops');
assertContains(webRTCSessionHook, "filter: `conversation_id=eq.${conversationId}`", 'WebRTC realtime channel is scoped to the active conversation');
assertContains(webRTCSessionHook, 'WEBRTC_SIGNAL_RETENTION_MS', 'WebRTC hook defines stale signaling retention');
assertContains(webRTCSessionHook, 'WEBRTC_CAMERA_READY_BURST_COUNT', 'WebRTC hook repeats camera-ready hints to recover missed realtime inserts');
assertContains(webRTCSessionHook, 'WEBRTC_SIGNAL_CATCHUP_INTERVAL_MS', 'WebRTC hook polls recent persisted signals to recover missed realtime inserts');
assertContains(webRTCSessionHook, 'catchUpRecentSignals', 'WebRTC hook has a missed-signal catch-up path for late host/participant tabs');
assertContains(webRTCSessionHook, 'rememberSignal', 'WebRTC hook deduplicates realtime and catch-up signaling events');
assertContains(webRTCSessionHook, "connection.addTransceiver('video', { direction: 'recvonly' })", 'WebRTC hook creates receive-only video negotiation for host and non-camera peers');
assertContains(webRTCSessionHook, ".delete()\n      .eq('conversation_id', conversationId)\n      .eq('event_type', WEBRTC_EVENT_TYPE)\n      .lt('created_at', cutoff)", 'WebRTC hook deletes stale session_events signals');
assertContains(webRTCSessionHook, 'VITE_WEBRTC_TURN_URLS', 'WebRTC hook supports deploy-time TURN server configuration');
assertContains(webRTCSessionHook, 'connectionStatus', 'WebRTC hook returns room-level connection status');
assertContains(webRTCSessionHook, 'peerStatuses', 'WebRTC hook returns per-peer connection status');
assertContains(facilitatorVoice, 'waitForVoices', 'facilitator voice waits for async browser voice loading');
assertContains(facilitatorVoice, 'NATURAL_VOICE_KEYWORDS', 'facilitator voice prefers higher quality browser voices');
assertContains(facilitatorVoice, 'selectBestVoice', 'facilitator voice uses scored voice selection');
assertContains(facilitatorVoice, 'utterance.rate = 0.92', 'facilitator voice uses a calmer speaking rate');
assertContains(phase3RuntimeService, 'message_id: input.messageId != null ? String(input.messageId) : null', 'TTS persistence stores message ids as strings to match backend schema');
assertContains(phase3RuntimeService, 'export async function hasTtsEventForMessage', 'TTS runtime exposes refresh replay guard lookup');
assertContains(phase3RuntimeService, ".eq('message_id', String(messageId))", 'TTS replay guard queries by serialized message id');
assertContains(vercelConfig, 'camera=(self)', 'deployed permissions policy allows same-origin participant camera preview');

console.log('UX session shell regression checks passed.');
