import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';

const repoRoot = process.cwd();
const read = (relativePath) => fs.readFileSync(path.join(repoRoot, relativePath), 'utf8');

const participantView = read('src/components/session/messaging/ParticipantMessagingView.tsx');
const sessionPage = read('src/pages/Session.tsx');
const inputFooter = read('src/components/session/InputFooter.tsx');
const hostContent = read('src/components/session/host/HostSessionContent.tsx');
const hostMessagingView = read('src/components/session/messaging/SimplifiedHostMessagingView.tsx');
const hostSessionsDropdown = read('src/components/session/host/SessionsDropdown.tsx');
const preSessionHostView = read('src/components/session/host/PreSessionHostView.tsx');
const facilitatorVoice = read('src/hooks/facilitator/useFacilitatorVoice.ts');
const stylesheet = read('src/index.css');
const videoGrid = read('src/components/session/video/SessionVideoGrid.tsx');
const preJoinMediaCheck = read('src/components/session/PreJoinMediaCheck.tsx');
const webRTCSessionHook = read('src/hooks/useWebRTCSession.ts');
const sessionContent = read('src/components/session/SessionContent.tsx');
const sessionStateRenderer = read('src/components/session/SessionStateRenderer.tsx');
const sessionPageState = read('src/hooks/useSessionPageState.ts');
const phase3RuntimeService = read('src/services/facilitator/phase3RuntimeService.ts');
const apiClient = read('src/lib/api.ts');
const vercelConfig = read('vercel.json');
const realtimeHelpers = read('src/utils/realtimeHelpers.ts');
const requestDeduplication = read('src/utils/requestDeduplication.ts');
const fastApiServer = read('supabase_proxy/server_fastapi.py');
const protectedHostRoute = read('src/components/ProtectedHostRoute.tsx');
const appRoutes = read('src/App.tsx');
const forgotPasswordPage = read('src/pages/ForgotPassword.tsx');
const resetPasswordPage = read('src/pages/ResetPassword.tsx');

const assertContains = (source, needle, label) => {
  assert.ok(source.includes(needle), `${label} should include ${needle}`);
};

const assertNotContains = (source, needle, label) => {
  assert.ok(!source.includes(needle), `${label} should not include ${needle}`);
};

assertContains(participantView, 'AI in room', 'participant room-gallery documentation');
assertContains(participantView, 'session-redesign-shell flex h-full flex-col overflow-hidden text-slate-900', 'participant redesigned light shell surface');
assertContains(participantView, 'Facilitator tile is shown with everyone else', 'participant renders the AI facilitator as a normal room tile instead of an oversized spotlight');
assertContains(participantView, 'Current question', 'participant current-question card');
assertContains(participantView, 'latestOwnParticipantMessage', 'participant registered-response derivation');
assertContains(participantView, 'String(message.participant) === participantKey', 'participant response registration tolerates numeric participant ids');
assertContains(participantView, 'Your response is registered', 'participant visible response confirmation');
assertContains(participantView, 'effectiveResponseCount', 'participant response counter uses local registration fallback');
assertContains(participantView, 'Math.max(isOpenDiscussionMode ? responseCount : 0, hasRegisteredResponse ? 1 : 0)', 'participant local response counter preserves own completion without leaking prior open-discussion counts into structured modes');
assertContains(participantView, "type SidebarTab = 'people' | 'chat'", 'participant people/chat sidebar contract');
assertContains(participantView, "aria-pressed={sidebarTab === 'people'}", 'participant mobile People tab exposes active pressed state');
assertContains(participantView, "aria-pressed={sidebarTab === 'chat'}", 'participant mobile Chat tab exposes active pressed state');
assertContains(participantView, "{sidebarTab === 'people' ? renderPeoplePanel('mobile') : renderChatPanel('mobile')}", 'participant mobile tabs render a visible People or Chat panel');
assertContains(participantView, '<SessionVideoGrid', 'participant People tab multi-video grid integration');
assertContains(participantView, 'variant="participant-sidebar"', 'participant sidebar video grid variant');
assertContains(participantView, 'participantVideoTiles', 'participant data-driven video tile mapping');
assertContains(participantView, 'navigator.mediaDevices.getUserMedia', 'participant local camera permission request');
assertContains(participantView, 'localCameraStartPromiseRef', 'participant camera permission requests are single-flight guarded');
assertContains(participantView, 'localCameraRequestIdRef.current !== requestId', 'participant camera ignores stale permission results');
assertContains(participantView, 'localCameraStartPromiseRef.current) return', 'participant camera toggle does not launch duplicate permission prompts while starting');
assertContains(participantView, 'readParticipantMediaPreferences(conversationId)', 'participant refresh restores previously enabled media preferences after rejoin');
assertContains(participantView, 'persistMediaPreferences(true, hasAudioTrack)', 'participant camera startup persists camera-on media preference for reload recovery');
assertContains(participantView, 'persistMediaPreferences(false, false)', 'participant explicit camera-off clears reload recovery preference');
assertContains(participantView, 'persistParticipantMediaPreferences(conversationId', 'participant media preferences are scoped to the active conversation');
assertContains(participantView, 'localCameraStreamRef.current.getTracks().forEach((track) => track.stop())', 'participant local camera stream cleanup');
assertContains(participantView, 'data-camera-toggle="participant-local-preview"', 'participant header camera toggle marker');
assertContains(participantView, 'data-camera-toggle={`participant-${panelVariant}-preview`}', 'participant shared People panel camera toggle marker covers desktop and mobile');
assertContains(participantView, 'handleToggleLocalCameraClick', 'participant camera toggles use a guarded click handler');
assertContains(participantView, 'event.preventDefault();', 'participant camera toggle prevents accidental form submission or navigation');
assertContains(participantView, 'event.stopPropagation();', 'participant camera toggle avoids parent click side effects');
assertContains(participantView, 'useWebRTCSession({', 'participant initializes WebRTC signaling for remote video tiles');
assertContains(participantView, "role: 'participant'", 'participant WebRTC hook runs in participant role');
assertContains(participantView, 'mediaStream: isCurrentUser ? localCameraStream : remoteStream', 'participant self tile uses local stream and remote tiles use peer streams');
assertContains(participantView, 'roomConnectionLabel', 'participant exposes WebRTC room connection status for live QA');
assertContains(participantView, 'connectionStatusLabel', 'participant remote tiles expose peer connection labels');
assertContains(participantView, 'Camera access was blocked', 'participant camera permission feedback');
assertContains(participantView, "connectionStatusLabel: aiIsSpeaking ? 'AI speaking'", 'participant AI speaking visualization is surfaced on the facilitator tile');
assertContains(participantView, '<InputFooter', 'participant preserved composer integration');
assertContains(participantView, 'await submitModeInput({', 'participant mode input plumbing');
assertContains(participantView, 'modeOptions={modeChoices}', 'participant passes dynamic vote and reflection options to adaptive footer');
assertContains(participantView, "onVote={(choice) => void handleSubmitModeChoice(choice, 'vote')}", 'participant wires voting selection callbacks into mode submission');
assertContains(participantView, "onWordPick={(choice) => void handleSubmitModeChoice(choice, 'reflection_word')}", 'participant wires reflection word callbacks into mode submission');
assertContains(participantView, "const isOpenDiscussionMode = effectiveModeKey === 'open_discussion';", 'participant explicitly recognizes effective adaptive open discussion as a free-floor mode');
assertContains(participantView, 'modeBlocksAfterResponse', 'participant only blocks repeat composer use for restricted facilitation modes');
assertContains(participantView, 'const audioOnlyStream = new MediaStream([audioTrack]);', 'participant microphone can create an audio-only live stream for free speaking');
assertContains(participantView, "{microphoneEnabled ? 'Mic on' : 'Muted'}", 'participant status reflects live microphone state independently of text dictation');
assertContains(inputFooter, "isOpenDiscussionMode || lastMessage?.sender === 'assistant'", 'adaptive footer keeps Open Discussion composer available after participant contributions');
assertContains(inputFooter, "const shouldRenderDefaultChatInput = !modeContext && !isPaused && !isSkipped;", 'adaptive footer suppresses the fallback ChatInput when a facilitation-mode footer is already rendered');
assertContains(inputFooter, "You're live — speak freely", 'adaptive footer explains Open Discussion as a free-speaking mode');
assertContains(sessionContent, "key={isAdmin ? connectionAttempts : 'participant-stable'}", 'participant session provider remains mounted during transient retries to avoid refresh-like resets');
assertContains(sessionPageState, 'shouldPreserveParticipantView', 'participant retry preserves the live room instead of returning to the loading shell');
assertContains(sessionStateRenderer, "error=\"This session link is missing required session information.", 'session renderer retains a recoverable missing-context guard');
assertContains(sessionPage, 'const isBareParticipantSessionRoute', 'session page detects a bare participant route before mounting the provider overlay');
assertContains(sessionPage, '<JoinSessionLoadingState', 'session page renders a page-level missing-context guard for bare participant deep links');
assertContains(inputFooter, "modeKey === 'voting_rating'", 'adaptive footer renders voting mode panel');
assertContains(inputFooter, "modeKey === 'round_robin'", 'adaptive footer renders round robin turn-gated panel');
assertContains(inputFooter, "modeKey === 'silent_individual_response'", 'adaptive footer renders private silent response panel');
assertContains(inputFooter, "modeKey === 'reflection_checkin'", 'adaptive footer renders reflection word-pick panel');
assertContains(inputFooter, "modeKey === 'debate'", 'adaptive footer renders debate hand-raise panel');
assertContains(inputFooter, "return renderOpenDiscussionPanel();", 'adaptive footer defaults to open discussion panel');
assertContains(inputFooter, 'sm:grid-cols-2', 'adaptive footer keeps voting choices responsive across columns');
assertContains(inputFooter, 'max-h-[260px] overflow-y-auto', 'adaptive footer enforces mobile footer max height with internal scroll');
assertContains(inputFooter, 'aria-label={`Vote for ${choice.label}`}', 'adaptive footer gives vote buttons accessible labels');
assertContains(inputFooter, 'aria-pressed={handRaised || floorGranted}', 'adaptive footer exposes debate hand raise pressed state');
assertContains(inputFooter, 'Silent response mode is active', 'adaptive footer announces silent response privacy to screen readers');
assertContains(inputFooter, 'Facilitation mode changed. Unsaved draft input was cleared.', 'adaptive footer announces mode transitions and draft clearing');
assertContains(inputFooter, 'motion-reduce:transition-none', 'adaptive footer respects reduced motion preferences');
assertContains(participantView, 'speechEnabled={speechStackEnabled && !aiIsSpeaking}', 'participant speech runtime requires enabled settings and pauses during AI speech');
assertContains(participantView, 'hasTtsEventForMessage', 'participant skips facilitator TTS replay after refresh when a TTS event already exists');
assertContains(participantView, 'const messageId = String(lastAssistantMessage.id);', 'participant serializes assistant message id before speech tracking');
assertContains(participantView, 'lastSpokenAssistantMessageRef.current = messageId;', 'participant speech replay guard uses serialized message id');

assertContains(hostContent, 'PanelGroup direction="horizontal"', 'host resizable command center');
assertContains(hostContent, 'session-redesign-shell flex min-h-0 flex-1 flex-col overflow-hidden p-3 text-slate-900', 'host redesigned light command-center surface');
assertContains(stylesheet, '.session-glass-panel', 'shared redesign glass-panel utility');
assertContains(stylesheet, '.session-progress-fill', 'shared redesign progress utility');
assertContains(hostContent, 'Participant intelligence', 'host participant intelligence rail');
assertContains(hostContent, 'Session pulse', 'host pulse panel');
assertContains(hostContent, '<SimplifiedHostMessagingView', 'host preserved control surface');
assertContains(hostContent, 'inferFacilitatorVoiceGender({', 'host derives facilitator voice gender from facilitator metadata');
assertContains(hostContent, "const facilitatorVoiceLabel = 'Persona-matched voice';", 'host header identifies persona-resolved voice routing');
assertContains(hostContent, 'TTS: {facilitatorVoiceLabel}', 'host header surfaces the persona-matched TTS routing state');
assertContains(hostContent, 'Panel defaultSize={26} minSize={22} maxSize={34}', 'host allocates a readable default width to the control and transcript panel');
assertContains(hostContent, 'facilitatorVoiceGender={facilitatorVoiceGender}', 'host passes facilitator voice gender into the command surface');
assertContains(hostContent, 'Facilitator voice', 'host session pulse includes facilitator voice context for TTS QA');
assertContains(hostMessagingView, 'Next facilitation move', 'host overview promotes a single action-first command surface');
assertContains(hostMessagingView, 'Generate next turn', 'host command center makes the primary next action visible without scrolling');
assertContains(hostMessagingView, 'AI capabilities', 'host overview compresses secondary toolbox information into a quiet capability summary');
assertContains(hostMessagingView, 'Quiet context only; the host does not need to manage these during the live flow.', 'host overview reduces explanatory density for secondary capability context');
assertContains(hostMessagingView, "const facilitatorVoiceLabel = 'Persona-matched voice';", 'host command center uses accurate persona voice wording');
assertContains(hostMessagingView, 'TTS: {facilitatorVoiceLabel}', 'host command center displays the persona-matched TTS routing state');
assertContains(hostSessionsDropdown, 'Open sessions', 'host session switcher does not mislabel historic open sessions as live-only');
assertContains(hostSessionsDropdown, 'No other open sessions', 'host empty session switcher state uses accurate open-session terminology');
assertNotContains(hostMessagingView, 'Participant counts and live response metrics stay in the side rails', 'host overview removes meta-explanatory layout copy from the visible command surface');
assertNotContains(hostMessagingView, 'Metric Strip', 'host overview removes duplicated metric strip from the central workspace');
assertNotContains(hostMessagingView, 'Session Details', 'host overview removes duplicated session details from the central workspace');
assertNotContains(hostMessagingView, 'icon:', 'host quick-instruction presets avoid decorative emoji/icon noise in the professional command surface');
assertContains(hostContent, 'Video room', 'host multi-video room section');
assertContains(hostContent, "videoLayout === 'gallery'", 'host gallery-mode toggle');
assertContains(hostContent, '<SessionVideoTile', 'host spotlight video tile');
assertContains(hostContent, 'variant="host-strip"', 'host participant thumbnail strip');
assertContains(hostContent, 'showResponseStatus', 'host response status badges on video tiles');
assertContains(hostContent, 'useWebRTCSession({', 'host initializes WebRTC signaling for participant cameras');
assertContains(hostContent, "role: 'host'", 'host WebRTC hook runs in receive-only host role');
assertContains(hostContent, 'mediaStream: remoteStream', 'host participant video tiles consume remote MediaStreams');
assertContains(hostContent, 'const shouldEnableHostVideoRoom = Boolean(currentConversationId) && !isSessionEnded;', 'host WebRTC receiver stays enabled before formal session start so participant camera offers can complete');
assertContains(hostContent, 'enabled: shouldEnableHostVideoRoom', 'host WebRTC hook uses the pre-start receiver enablement guard');
assertNotContains(hostContent, 'enabled: isSessionStarted && !isSessionEnded', 'host WebRTC receiver must not stay disabled during pre-start participant camera checks');
assertContains(hostContent, 'videoRoomStatusLabel', 'host video room exposes WebRTC room connection status for live QA');
assertContains(hostContent, 'connectionStatusLabel: formatPeerTileStatusLabel(tileConnectionStatus)', 'host participant tiles expose peer connection labels');
assertContains(hostContent, 'onApproveMode={onApproveMode}', 'host mode approval plumbing');
assertContains(preSessionHostView, 'const isSessionStarted = Boolean(conversationData?.session_started);', 'pre-session host view derives live state from conversation data');
assertContains(preSessionHostView, 'isSessionStarted={isSessionStarted}', 'pre-session host start button reflects active sessions');
assertNotContains(preSessionHostView, 'isSessionStarted={false}', 'pre-session host start button must not be hard-coded inactive');
assertNotContains(hostContent, "UX handoff's dark", 'host design documentation');
assertNotContains(participantView, 'Precision Dark', 'participant design documentation');

assertContains(stylesheet, "font-family: 'Sora'", 'Signal & Clarity display font token');
assertContains(stylesheet, '@keyframes aiSpeakingPulse', 'AI speaking pulse animation');
assertContains(stylesheet, '@keyframes soundBar', 'sound bar animation');
assertContains(stylesheet, '@keyframes reactionPop', 'video reaction badge animation');

assertContains(videoGrid, 'mediaStream?: MediaStream | null', 'video tile optional live stream support');
assertContains(videoGrid, 'srcObject = stream', 'video tile MediaStream binding');
assertContains(videoGrid, 'videoElement.play()', 'video tile explicitly starts MediaStream playback after permission');
assertContains(videoGrid, "videoElement.addEventListener('loadedmetadata', playStream)", 'video tile retries playback when stream metadata becomes available');
assertContains(videoGrid, "videoElement.addEventListener('canplay', playStream)", 'video tile retries playback when mobile browsers report the stream can play');
assertContains(videoGrid, "track.addEventListener('unmute', schedulePlaybackRetry)", 'video tile retries playback when mobile camera tracks unmute after permission');
assertContains(videoGrid, 'srcObject = null', 'video tile MediaStream detaches on unmount');
assertContains(videoGrid, 'aria-label={`${name} live video`}', 'video tile accessible live preview label');
assertContains(preJoinMediaCheck, 'previewCleanupRef', 'pre-join camera preview owns cleanup for mobile playback listeners');
assertContains(preJoinMediaCheck, "videoElement.addEventListener('loadedmetadata', tryPlay)", 'pre-join camera preview retries playback when stream metadata becomes available');
assertContains(preJoinMediaCheck, "videoElement.addEventListener('canplay', tryPlay)", 'pre-join camera preview retries playback when mobile browsers report the stream can play');
assertContains(preJoinMediaCheck, "track.addEventListener('unmute', schedulePlaybackRetry)", 'pre-join camera preview retries playback when mobile camera tracks unmute after permission');
assertContains(preJoinMediaCheck, "videoElement.removeEventListener('canplay', tryPlay)", 'pre-join camera preview removes mobile playback retry listeners during cleanup');
assertContains(videoGrid, "data-session-video-grid", 'video grid semantic marker');
assertContains(videoGrid, "data-video-tile-variant", 'video tile variant semantic marker');
assertContains(videoGrid, "variant?: 'participant-sidebar' | 'host-strip' | 'host-gallery'", 'video grid supported layout variants');
assertContains(videoGrid, 'data-connection-status={participant.connectionStatus}', 'video tile exposes peer connection status for smoke tests');
assertContains(videoGrid, 'connectionStatusLabel', 'video tile renders human-readable connection status labels');
assertContains(webRTCSessionHook, "event_type: WEBRTC_EVENT_TYPE", 'WebRTC signaling persists as session_events rows');
assertContains(webRTCSessionHook, "signalType: 'offer'", 'WebRTC hook sends SDP offers');
assertContains(webRTCSessionHook, "signalType: 'answer'", 'WebRTC hook sends SDP answers');
assertContains(webRTCSessionHook, "signalType: 'ice-candidate'", 'WebRTC hook sends ICE candidates');
assertContains(webRTCSessionHook, "signalType: 'camera-ready'", 'WebRTC hook supports camera-ready renegotiation hints');
assertContains(webRTCSessionHook, "signalType: 'camera-stopped'", 'WebRTC hook tears down remote streams when a camera stops');
assertContains(webRTCSessionHook, "filter: `conversation_id=eq.${conversationId}`", 'WebRTC realtime channel is scoped to the active conversation');
assertContains(webRTCSessionHook, 'WEBRTC_SIGNAL_RETENTION_MS', 'WebRTC hook defines stale signaling retention');
assertContains(webRTCSessionHook, 'WEBRTC_CAMERA_READY_BURST_COUNT', 'WebRTC hook repeats camera-ready hints to recover missed realtime inserts');
assertContains(webRTCSessionHook, 'WEBRTC_SIGNAL_CATCHUP_INTERVAL_MS', 'WebRTC hook polls recent persisted signals to recover missed realtime inserts');
assertContains(webRTCSessionHook, 'catchUpRecentSignals', 'WebRTC hook has a missed-signal catch-up path for late host/participant tabs');
assertContains(webRTCSessionHook, 'rememberSignal', 'WebRTC hook deduplicates realtime and catch-up signaling events');
assertContains(webRTCSessionHook, "connection.addTransceiver('video', { direction: videoTrack ? 'sendrecv' : 'recvonly' })", 'WebRTC hook creates stable video negotiation for camera-on and non-camera peers');
assertContains(webRTCSessionHook, ".delete()\n      .eq('conversation_id', conversationId)\n      .eq('event_type', WEBRTC_EVENT_TYPE)\n      .lt('created_at', cutoff)", 'WebRTC hook deletes stale session_events signals');
assertContains(webRTCSessionHook, 'VITE_WEBRTC_TURN_URLS', 'WebRTC hook supports deploy-time TURN server configuration');
assertContains(webRTCSessionHook, 'connectionStatus', 'WebRTC hook returns room-level connection status');
assertContains(webRTCSessionHook, 'peerStatuses', 'WebRTC hook returns per-peer connection status');
assertContains(webRTCSessionHook, 'diagnostics', 'WebRTC hook returns browser-visible diagnostics for video troubleshooting');
assertContains(webRTCSessionHook, 'localCandidateTypes', 'WebRTC hook captures local ICE candidate types for diagnostics');
assertContains(webRTCSessionHook, 'remoteCandidateTypes', 'WebRTC hook captures remote ICE candidate types for diagnostics');
assertContains(webRTCSessionHook, 'receiverTrackStates', 'WebRTC hook exposes receiver tracks in diagnostics when ICE connects without visible media');
assertContains(webRTCSessionHook, 'syncRemoteReceiverStream', 'WebRTC hook synthesizes remote streams from receiver tracks when ontrack stream payloads are missing');
assertContains(webRTCSessionHook, 'record.connection.getReceivers()', 'WebRTC hook inspects receiver tracks when ICE connects without a visible media stream');
assertContains(webRTCSessionHook, 'stream.addTrack(track);', 'WebRTC hook builds a fallback MediaStream from received remote tracks');
assertContains(webRTCSessionHook, 'WEBRTC_SIGNAL_CRITICAL_RETRY_COUNT', 'WebRTC hook retries critical SDP offer and answer inserts so participants do not remain stuck in have-local-offer');
assertContains(webRTCSessionHook, "record.connection.signalingState !== 'have-local-offer'", 'WebRTC hook ignores late or duplicate SDP answers once the peer is already stable');
assertContains(webRTCSessionHook, 'await syncLocalStreamToPeer(record, localStreamRef.current);', 'WebRTC answerer syncs local camera stream only after applying the remote offer');
assertContains(webRTCSessionHook, "role === 'participant' && peerId === HOST_PEER_ID", 'WebRTC participant actively creates the offer to the host when its camera is live');
assertNotContains(webRTCSessionHook, '!localStream || !hasRealtimeSupport', 'WebRTC peer readiness is not blocked by a missing local stream after participant refresh');
assertContains(webRTCSessionHook, 'const announcePeerReady = () => {', 'WebRTC refresh/rejoin announces peer readiness even before camera restoration completes');
assertContains(webRTCSessionHook, "role === 'host' && peerId !== HOST_PEER_ID", 'WebRTC host waits for participant offers to avoid glare and ghost peer bootstraps');
assertContains(webRTCSessionHook, 'if (!isLocalOffererForPeer(peerId)) return;', 'WebRTC createOffer is guarded so non-offerer reconnect paths cannot create glare');
assertContains(participantView, 'resolvePositiveParticipantId', 'Participant video shell rejects participant-0 identity fallbacks');
assertContains(participantView, 'getParticipantIdFromUrl', 'Participant video shell can recover the joined participant id from the URL');
assertContains(participantView, 'firstKnownParticipantId', 'Participant video shell falls back to the known participant record when identity is delayed');
assertContains(facilitatorVoice, 'waitForVoices', 'facilitator voice waits for async browser voice loading');
assertContains(facilitatorVoice, 'NATURAL_VOICE_KEYWORDS', 'facilitator voice prefers higher quality browser voices');
assertContains(facilitatorVoice, 'selectBestVoice', 'facilitator voice uses scored voice selection');
assertContains(facilitatorVoice, 'utterance.rate = 0.92', 'facilitator voice uses a calmer speaking rate');
assertContains(phase3RuntimeService, 'const serializedMessageId = input.messageId != null ? String(input.messageId) : null', 'TTS persistence serializes message ids before insertion');
assertContains(phase3RuntimeService, 'message_id: serializedMessageId', 'TTS persistence stores message ids as strings to match backend schema');
assertContains(phase3RuntimeService, 'export async function hasTtsEventForMessage', 'TTS runtime exposes refresh replay guard lookup');
assertContains(phase3RuntimeService, 'const serializedMessageId = String(messageId);', 'TTS replay guard serializes message ids before lookup');
assertContains(phase3RuntimeService, ".eq('message_id', serializedMessageId)", 'TTS replay guard queries by serialized message id');
assertContains(apiClient, 'RAILWAY_DEV_PROXY_PREFIX = "/__railway_dev"', 'API client defines same-origin dev Railway realtime proxy prefix');
assertContains(apiClient, 'RAILWAY_PROD_PROXY_PREFIX = "/__railway_prod"', 'API client defines same-origin production Railway realtime proxy prefix');
assertContains(apiClient, 'getRailwayRealtimeProxyPrefix', 'API client selects a same-origin realtime proxy on deployed browser origins');
assertContains(apiClient, 'requestRealtimeTicket(topic)', 'SSE subscriptions acquire an authorized conversation-scoped ticket');
assertContains(apiClient, 'buildRealtimeSseUrl(topic, ticket)', 'SSE subscriptions use centralized scoped-ticket URL construction');
assertContains(apiClient, 'new EventSource(url)', 'Realtime manager opens EventSource using the CORS-safe URL');
assertContains(apiClient, 'private normalizeFilterValue(col: string, val: unknown): unknown', 'API query builder centralizes table-specific filter serialization');
assertContains(apiClient, "this.s.table === 'facilitator_tts_events' && col === 'message_id'", 'API query builder serializes facilitator TTS message_id filters as strings');
assertContains(apiClient, 'private normalizeMutationBody(value: unknown): unknown', 'API query builder normalizes facilitator TTS mutation bodies');
assertContains(apiClient, 'next.message_id = String(next.message_id)', 'API query builder serializes facilitator TTS message_id mutation bodies as strings');
assertContains(apiClient, 'filter(col: string, op: string, val: unknown): this { this.filters.push([col, `${op}.${this.normalizeFilterValue(col, val)}`]); return this; }', 'Mutation builder serializes generic message_id filters as strings');
assertContains(apiClient, 'match(obj: Record<string, unknown>): this { Object.entries(obj).forEach(([k, v]) => this.filters.push([k, `eq.${this.normalizeFilterValue(k, v)}`])); return this; }', 'Mutation builder serializes message_id match filters as strings');
assertContains(fastApiServer, 'def build_where(params: dict, table: str | None = None):', 'Backend REST filters are table-aware for schema-specific coercion');
assertContains(fastApiServer, 'table == "facilitator_tts_events" and column == "message_id"', 'Backend REST filters keep facilitator TTS message_id as text');
assertContains(fastApiServer, 'table == "facilitator_tts_events" and k == "message_id" and v is not None', 'Backend REST writes keep facilitator TTS message_id as text');
assertContains(fastApiServer, 'wc, wv = build_where(params, table)', 'Backend REST handler passes table context into filter coercion');
assertContains(vercelConfig, '"source": "/__railway_dev/(.*)"', 'Vercel rewrites development realtime proxy before the SPA catch-all');
assertContains(vercelConfig, '"destination": "https://friendly-ai-sessions-development.up.railway.app/$1"', 'Vercel development proxy targets Railway dev backend');
assertContains(vercelConfig, '"source": "/__railway_prod/(.*)"', 'Vercel rewrites production realtime proxy before the SPA catch-all');
assertContains(vercelConfig, '"destination": "https://friendly-ai-sessions-production.up.railway.app/$1"', 'Vercel production proxy targets Railway production backend');
assertContains(vercelConfig, 'camera=(self)', 'deployed permissions policy allows same-origin participant camera preview');
assertContains(realtimeHelpers, 'void Promise.resolve(channel.unsubscribe()).catch(swallowExpectedRemovalError)', 'realtime helper catches async unsubscribe abort rejections');
assertContains(realtimeHelpers, 'void Promise.resolve(api.removeChannel(channel)).catch(swallowExpectedRemovalError)', 'realtime helper catches async removeChannel abort rejections');
assertContains(requestDeduplication, 'void promise.then(', 'request deduplication cleanup handles rejected participant-load promises without creating unhandled finally rejections');
assertNotContains(requestDeduplication, 'promise.finally(', 'request deduplication must not attach bare finally cleanup to abortable participant-load promises');
assertContains(appRoutes, 'const ForgotPassword = lazy(() => import("./pages/ForgotPassword"));', 'forgot-password page is registered as a lazy route');
assertContains(appRoutes, '<Route path="/forgot-password" element={<ForgotPassword />} />', 'forgot-password path renders a public password-reset request page');
assertContains(forgotPasswordPage, 'await resetPassword(trimmedEmail);', 'forgot-password page sends the existing password reset email flow');
assertContains(forgotPasswordPage, 'Check your email', 'forgot-password page renders a non-404 success state');
assertContains(resetPasswordPage, "navigate('/forgot-password')", 'expired reset-token CTA sends users to request a new link');
assertContains(protectedHostRoute, "setHostRouteError('missing-session')", 'direct host route without a session id records missing-context state');
assertContains(protectedHostRoute, 'Missing host session', 'direct host route renders a missing-session recovery message');
assertContains(protectedHostRoute, '<Link to="/my-facilitators">Back to facilitators</Link>', 'direct host route provides a dashboard recovery action instead of redirecting into participant loading');

console.log('UX session shell regression checks passed.');
