-- Create editable persona configuration records for AI facilitators.
-- Apply this migration to the development Supabase project first.

create table if not exists public.facilitator_persona_configs (
  id bigint generated by default as identity primary key,
  facilitator_id bigint not null unique references public.facilitators(id) on delete cascade,
  display_name text null,
  pronouns text[] null,
  gender_presentation text null,
  voice_id text null,
  voice_provider text null,
  voice_style text null,
  avatar_style text null,
  avatar_asset_url text null,
  locale text null,
  tone text null,
  animation_preset text null,
  nonverbal_behavior jsonb not null default '{}'::jsonb,
  speaking_behavior jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint facilitator_persona_configs_gender_presentation_check
    check (
      gender_presentation is null
      or gender_presentation in (
        'feminine',
        'masculine',
        'neutral',
        'non_binary',
        'androgynous',
        'custom'
      )
    )
);

comment on table public.facilitator_persona_configs is
  'Editable persona, voice, avatar, and behavioral presentation settings for each facilitator.';

comment on column public.facilitator_persona_configs.gender_presentation is
  'Optional avatar/persona presentation label. This is not intended to represent biological sex.';

comment on column public.facilitator_persona_configs.pronouns is
  'Optional editable pronouns for display and prompt/persona construction.';

comment on column public.facilitator_persona_configs.nonverbal_behavior is
  'JSON settings for avatar listening cues such as gaze, nodding, blinking, posture, and gestures.';

comment on column public.facilitator_persona_configs.speaking_behavior is
  'JSON settings for speaking style such as pace, pauses, interruption restraint, and prosody.';

create index if not exists facilitator_persona_configs_facilitator_id_idx
  on public.facilitator_persona_configs(facilitator_id);

create index if not exists facilitator_persona_configs_voice_provider_idx
  on public.facilitator_persona_configs(voice_provider);

create or replace function public.set_facilitator_persona_configs_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_facilitator_persona_configs_updated_at
  on public.facilitator_persona_configs;

create trigger set_facilitator_persona_configs_updated_at
before update on public.facilitator_persona_configs
for each row
execute function public.set_facilitator_persona_configs_updated_at();

alter table public.facilitator_persona_configs enable row level security;

-- Persona settings must be readable anywhere facilitators are displayed.
-- If this becomes sensitive later, narrow the policy to authenticated users or session participants.
drop policy if exists "Facilitator persona configs are publicly readable"
  on public.facilitator_persona_configs;

create policy "Facilitator persona configs are publicly readable"
  on public.facilitator_persona_configs
  for select
  using (true);

-- Owners can create persona config for their own facilitators.
drop policy if exists "Facilitator owners can create persona configs"
  on public.facilitator_persona_configs;

create policy "Facilitator owners can create persona configs"
  on public.facilitator_persona_configs
  for insert
  with check (
    exists (
      select 1
      from public.facilitators f
      where f.id = facilitator_persona_configs.facilitator_id
        and f.user_id = auth.uid()::text
    )
  );

-- Owners can update persona config for their own facilitators.
drop policy if exists "Facilitator owners can update persona configs"
  on public.facilitator_persona_configs;

create policy "Facilitator owners can update persona configs"
  on public.facilitator_persona_configs
  for update
  using (
    exists (
      select 1
      from public.facilitators f
      where f.id = facilitator_persona_configs.facilitator_id
        and f.user_id = auth.uid()::text
    )
  )
  with check (
    exists (
      select 1
      from public.facilitators f
      where f.id = facilitator_persona_configs.facilitator_id
        and f.user_id = auth.uid()::text
    )
  );

-- Owners can delete persona config for their own facilitators.
drop policy if exists "Facilitator owners can delete persona configs"
  on public.facilitator_persona_configs;

create policy "Facilitator owners can delete persona configs"
  on public.facilitator_persona_configs
  for delete
  using (
    exists (
      select 1
      from public.facilitators f
      where f.id = facilitator_persona_configs.facilitator_id
        and f.user_id = auth.uid()::text
    )
  );
