// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msahrdujupfcotujyluy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zYWhyZHVqdXBmY290dWp5bHV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1MDg0MzQsImV4cCI6MjA1NjA4NDQzNH0.JgNJp4N2i6_LSoWzmMeIHMvXcAQDqtiJ6QMap6afSg0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);