
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error('Missing Supabase environment variables. Please check your .env file.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Export the URL and key for use with Edge Functions
export const EDGE_FUNCTION_URL = SUPABASE_URL;
export const EDGE_FUNCTION_KEY = SUPABASE_PUBLISHABLE_KEY;

// Disable realtime for local development to prevent WebSocket connection issues
const isLocalDev = SUPABASE_URL.includes('localhost') || SUPABASE_URL.includes('127.0.0.1');

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    realtime: isLocalDev ? { params: { eventsPerSecond: 0 } } : undefined,
    auth: {
        autoRefreshToken: !isLocalDev,
        persistSession: true,
        detectSessionInUrl: !isLocalDev,
    },
});
